POST http://localhost:9136/resources
Content-Type: application/json

{
  "name": "cheese",
  "description": "cheese bruh",
  "price": 100,
  "quantity": 0.1,
  "unit": "pcs"
}

### 

GET http://localhost:9136/resources

###
GET http://localhost:9136/templates

###

GET http://localhost:9136/templates/1

###
POST http://localhost:9136/templates
Content-Type: application/json

{
  "name": "Pizza",
  "description": "Plantilla actualizada con recursos correctamente estructurados",
  "quantity": 1,
  "unit": "pcs",
  "difficulty": 5,
  "steps": [
    {
      "name": "Paso 1",
      "instructions": "Instrucciones del primer paso"
    },
    {
      "name": "Paso 2",
      "instructions": "Instrucciones del segundo paso"
    }
  ],
  "resources": [
    {
      "resource_id": 1,
      "quantity": 50,
      "unit": "g"
    }
  ]
}


###

PUT http://localhost:9136/templates/1
Content-Type: application/json

{
  "name": "queso",
  "description": "Top 3 hijos que sus padres estan abandonados",
  "quantity": 1,
  "unit": "Pieces",
  "difficulty": 5,
  "steps": [
    {"name": "PACACACACANOI", "instructions": "rumano"},
    {"name": "trippie", "instructions": "es un mojon"}
  ],
  "resources": [
    {"resource_id": 1},
    {"quantity": 50},
    {"unit": "Gram"}
  ]
  
}

###
DELETE http://localhost:9136/templates/1