components:
  schemas:
    CreateResourceRequestDTO:
      properties:
        description:
          type: string
        name:
          type: string
        price:
          type: integer
      type: object
    CreateTemplateRequestDTO:
      properties:
        description:
          type: string
        difficulty:
          type: integer
        name:
          type: string
        quantity:
          type: integer
        resources:
          items:
            $ref: "#/components/schemas/ResourceRefDTO"
          type: array
        steps:
          items:
            $ref: "#/components/schemas/StepDTO"
          type: array
        unit:
          type: string
      type: object
    ResourceJSONResponseDTO:
      properties:
        description:
          type: string
        id:
          type: integer
        name:
          type: string
        price:
          type: integer
      type: object
    ResourceRefDTO:
      properties:
        quantity:
          type: integer
        resource_id:
          type: integer
        unit:
          type: string
      type: object
    ResourceRefResponseDTO:
      properties:
        quantity:
          type: integer
        resource_id:
          type: integer
        unit:
          type: string
      type: object
    StepDTO:
      properties:
        instructions:
          type: string
        name:
          type: string
      type: object
    StepJSONResponseDTO:
      properties:
        instructions:
          type: string
        name:
          type: string
        order:
          type: integer
      type: object
    TemplateJSONResponseDTO:
      properties:
        description:
          type: string
        difficulty:
          type: integer
        id:
          type: integer
        name:
          type: string
        quantity:
          type: integer
        resources:
          items:
            $ref: "#/components/schemas/ResourceRefResponseDTO"
          type: array
        steps:
          items:
            $ref: "#/components/schemas/StepJSONResponseDTO"
          type: array
        unit:
          type: string
      type: object
    TemplateListJSONResponseDTO:
      properties:
        description:
          type: string
        id:
          type: integer
        name:
          type: string
      type: object
    UpdateResourceRequestDTO:
      properties:
        description:
          type: string
        id:
          type: integer
        name:
          type: string
        price:
          type: integer
      type: object
    UpdateTemplateRequestDTO:
      properties:
        description:
          type: string
        difficulty:
          type: integer
        id:
          type: integer
        name:
          type: string
        quantity:
          type: integer
        resources:
          items:
            $ref: "#/components/schemas/ResourceRefDTO"
          type: array
        steps:
          items:
            $ref: "#/components/schemas/StepDTO"
          type: array
        unit:
          type: string
      type: object
info:
  description: Optimize and control processes based on templates.
  title: Tarmo API
  version: 2.1.0
openapi: 3.0.0
paths:
  /resources:
    get:
      description: " Get a list of all resources in the collection"
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ResourceJSONResponseDTO"
                type: array
          description: ""
        "500":
          content:
            application/json:
              schema:
                type: string
          description: internal error
    post:
      description: " Add a new resource to the collection"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateResourceRequestDTO"
        required: true
      responses:
        "201":
          description: Created
        "400":
          content:
            application/json:
              schema:
                type: string
          description: invalid request
  /resources/{id}:
    delete:
      description: " Remove a resource from the collection"
      parameters:
        - description: Resource ID
          in: path
          name: id
          required: true
          schema:
            description: Resource ID
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                type: string
          description: invalid id
        "404":
          content:
            application/json:
              schema:
                type: string
          description: resource not found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: internal error
    get:
      description: " Get detailed information about a single resource"
      parameters:
        - description: Resource ID
          in: path
          name: id
          required: true
          schema:
            description: Resource ID
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceJSONResponseDTO"
          description: ""
        "400":
          content:
            application/json:
              schema:
                type: string
          description: invalid id
        "404":
          content:
            application/json:
              schema:
                type: string
          description: resource not found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: internal error
    put:
      description: " Update an existing resource's information"
      parameters:
        - description: Resource ID
          in: path
          name: id
          required: true
          schema:
            description: Resource ID
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateResourceRequestDTO"
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/json:
              schema:
                type: string
          description: invalid request
        "404":
          content:
            application/json:
              schema:
                type: string
          description: template not found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: internal error
  /templates:
    get:
      description: " Get a list of all templates in the collection"
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/TemplateListJSONResponseDTO"
                type: array
          description: ""
        "500":
          content:
            application/json:
              schema:
                type: string
          description: internal error
    post:
      description: " Add a new template to the collection"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTemplateRequestDTO"
        required: true
      responses:
        "201":
          description: Created
        "400":
          content:
            application/json:
              schema:
                type: string
          description: invalid request
  /templates/{id}:
    delete:
      description: " Remove a template from the collection"
      parameters:
        - description: Template ID
          in: path
          name: id
          required: true
          schema:
            description: Template ID
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                type: string
          description: invalid id
        "404":
          content:
            application/json:
              schema:
                type: string
          description: template not found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: internal error
    get:
      description: " Get detailed information about a single template"
      parameters:
        - description: Template ID
          in: path
          name: id
          required: true
          schema:
            description: Template ID
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateJSONResponseDTO"
          description: ""
        "400":
          content:
            application/json:
              schema:
                type: string
          description: invalid id
        "404":
          content:
            application/json:
              schema:
                type: string
          description: template not found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: internal error
    put:
      description: " Update an existing template's information"
      parameters:
        - description: Template ID
          in: path
          name: id
          required: true
          schema:
            description: Template ID
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTemplateRequestDTO"
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/json:
              schema:
                type: string
          description: invalid request
        "404":
          content:
            application/json:
              schema:
                type: string
          description: template not found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: internal error
servers:
  - description: Default Server URL
    url: /
