@host = localhost
@port = 9136
@baseUrl = http://{{host}}:{{port}}
@recipeId = 2

### GET: All recipes
GET {{baseUrl}}/recipes
Accept: application/json


### GET: recipe by ID
GET {{baseUrl}}/recipes/{{recipeId}}
Accept: application/json


### POST: create recipe
POST {{baseUrl}}/recipes
Content-Type: application/json

{
  "name": "Generic recipe",
  "description": "generic description",
  "quantity": "100",
  "unit": "g",
  "price": "10",
  "currency": "RON",
  "time": "30",
  "difficulty": "easy",
  "img_url": "unknown"
}


### DELETE: delete recipe by id
DELETE {{baseUrl}}/recipes/{{recipeId}}
Accept: application/json
